src/main/java/io/micronaut/gradle/graalvm/GraalUtil.java
Some version of the GraalVM JDK might not have `java.vendor.version` set
=> Modifies jvm system property to look for graalvm

src/main/java/io/micronaut/gradle/graalvm/NativeImageOptions.java, src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java
This PR removes the option `--no-server` because since GraalVM 20.2.0 is the default option. Also, the GraalVM team has mentioned some times that there are still issues when using a server for the build, so it's not really recommended to use it.
=> Remove '--no-server' because it's the default in GraalVM 20.2.0

src/main/java/io/micronaut/gradle/AnnotationProcessingConfigBuilder.java
This will fix the warning in IntelliJ IDEA:
Type AnnotationProcessingConfigBuilder! is inaccessible in this context due to: public/*package*/ interface AnnotationProcessingConfigBuilder defined in io.micronaut.gradle in file AnnotationProcessingConfigBuilder.class
=> Make AnnotationProcessingConfigBuilder public

.github/workflows/release.yml
We've lost all the tags since 1.0.0.RC1 (included). All the commits with the arrow are not commited into master branch (and lost)
=> Allow micronaut-build commit directly to master

src/main/java/io/micronaut/gradle/MicronautLibraryPlugin.java
This patch uses Gradle Api for Groovy Compiler(since Gradle 6) to setup compilation with parameters.
=> Use Groovy compiler options from Gradle Api

src/main/java/io/micronaut/gradle/MicronautExtension.java, src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
This fixes the case where you use a non-Graal JDK to build in which cases the `resource-config.json` is not generated
=> Apply graal annotation processor if native image tasks present in graph

.github/workflows/graalvm.yml, gradle.properties, src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, src/main/java/io/micronaut/gradle/graalvm/NativeImageTestTask.java, src/test/groovy/io/micronaut/gradle/NativeImageTestTaskSpec.groovy
This PR starts the native image server and configures Micronaut Test to use so that integration tests can also test the native image build
=> Allow running tests with the native image server

src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
When building the native image inside Docker, all the files in the GraalVM SDK are displayed when un-compressing the distribution. This PR removes the verbose flag so nothing is shown.
=> Do not display content of GraalVM SDK while uncompressing it on Docker

README.md, src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java, src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java
In relation to the issue that was raised ( https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/98 ) regarding the customisation of the Dockerfile generated, here is a PR that allows the addition of further instructions to be added.
The primary change was how the dockerfile and dockerfileNative tasks were being setup and executed.
=> Allowing a developer to add further instructions to the generated Dockerfile for additional customisation.

README.md
Add info block for configuring tasks in build.gradle.kts
Closes #113
=> docs: add info on configuring tasks in Kotlin

src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
The `latest` version of `frolvlad/alpine-glibc` (3.13) is not compatible with GraalVM and application fail with a segmentation fault. This PR sets the version to the previous one that works (3.12)
More info: https://github.com/oracle/graal/issues/3159
=> Use alpine-glibc:3.12 as base image

src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy, src/test/groovy/io/micronaut/gradle/LambdaNativeImageSpec.groovy
Fixes #132
This also fixes the discussion commented here https://github.com/orgs/micronaut-projects/teams/core-developers/discussions/103.
Basically:
`./gradlew nativeImage` sets the main class (`foo.Application`) as entry point for the native image
`./gradlew nativeImage -Pmicronaut.runtime=lambda` sets the main as to `io.micronaut.function.aws.runtime.MicronautLambdaRuntime` so the app can be deployed to AWS Lambda.
=> Set the right mainClass for apps deployed to AWS

src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java
When you execute a gradle task, this is output:
```
./gradlew buildNativeLambda
> Configure project :
DOESN'T EXIST!! = native-image
DOESN'T EXIST!! = native-image
```
I don't think we should have this print statement. Or if we want it it should use [Gradle logger](https://docs.gradle.org/current/userguide/logging.html) and it should not appear by default.
=> refactor: delete print statement

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java, src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, src/main/java/io/micronaut/gradle/docker/tasks/BuildLayersTask.java, src/test/groovy/io/micronaut/gradle/BuildLayersSpec.groovy
This merge request fixes issue with up-to-date check, which is currently applied only for a third build, because `.docker` folder is created in build directory after the first one, thus changing input for the `dockerBuild`.
Example of log from the second build:
```
Task ':analytics:computation-service:dockerBuild' is not up-to-date because:
Input property 'inputDir' file /home/ivan/IdeaProjects/computation-service/build/.docker has been added.
Input property 'inputDir' file /home/ivan/IdeaProjects/computation-service/build/.docker/analytics_computation-service_dockerBuild-imageId.txt has been added.
```
Also, there is a refactoring for `buildLayers` task which clearly defines its' config and makes its' cache key consistent when the `--build-cache` enabled. Thus, with some (tricky) …
=> Fix of up-to-date check for dockerBuild task and general improvements 

src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
A change occurred in GraalVM 21.1 whereby native libraries are no longer loaded from the current directly and explicitly setting java.library.path for any JNI libraries is now required.
=> Set java.library path for the native image.

README.md, build.gradle, src/main/java/io/micronaut/gradle/graalvm/GenerateResourceConfigFile.java, src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java, src/main/java/io/micronaut/gradle/graalvm/internal/ResourceConfigJsonWriter.java, src/test/groovy/io/micronaut/gradle/MicronautGraalPluginSpec.groovy, src/test/groovy/io/micronaut/gradle/graalvm/internal/ResourceConfigJsonWriterTest.groovy
This PR creates a new MicronautGraalVM plugin (that is automatically applied by Micronaut Application plugin) that generates GraalVM `resource-config.json` automatically.
After this and the same [PR for the Maven plugin](https://github.com/micronaut-projects/micronaut-maven-plugin/pull/184) are merged, we can remove the code that does this from GraalvmTypeElementVisitor in core (for Micronaut 3.0.x)
=> Create Micronaut GraalVM plugin and generate GraalVM resources file

src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java, src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
Referenced issue: #161
This PR adds support for base images that have either groupadd or addgroup. It check which one is available and based on that triggers command. Also, when specific group manipulation command is available, useradd has different syntax, so this is also reflected.
Tested with openjdk:16-alpine and oraclelinux:7
=> 2 variants of adding dedicated group and user

src/main/java/io/micronaut/gradle/MicronautApplicationPlugin.java, src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, src/test/groovy/io/micronaut/gradle/MicronautGraalPluginSpec.groovy
This commit adds support for generating the GraalVM resource-config.json file
even if the Micronaut Application plugin isn't applied (e.g if the application
plugin is).
This basically adds some null checks on extensions, but ideally the plugin should
react to different plugins being applied, and in particular the Micronaut
application plugin.
Fixes #223
=> Generate the GraalVM resource file even without the Micronaut application plugin

src/main/java/io/micronaut/gradle/graalvm/GraalUtil.java
In IntelliJ IDEA, the `java.vendor.version` property is inherited from IDEA's JDK, so `nativeImage` task is reporting this error message:
```
A GraalVM SDK is required to build native images
```
The `java.vendor` property is working well with value: "GraalVM Community"
See related issues here:
- https://youtrack.jetbrains.com/issue/IDEA-271768
- https://youtrack.jetbrains.com/issue/IDEA-268520
=> Fix detection of GraalVM in IntelliJ IDEA

src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
The generate docker image file contained paths to files on the host
instead of paths in the image builder. The consequence is that
resources files, and in particular `application.yml` file were
totally ignored.
This is a hotfix for this issue, but this is NOT a final fix: this
is a very dirty hack, which is going to be removed once we migrate
to the official GraalVM plugin.
Fixes #246
Fixes #243
=> Fix for incorrect paths in docker image file

src/main/java/io/micronaut/gradle/docker/tasks/BuildLayersTask.java
At the moment outputs of the `BuildLayersTask` are not cleared, what can lead to an incorrect build in the following scenario:
- Invoke `dockerBuild` on branch `main` with files `src/main/resources/res1.xml` and `src/main/resources/res2.xml`. The following files will be created by `BuildLayersTask` and will be present in the resulting image:  `build/docker/layers/resources/res1.xml `and `build/docker/layers/resources/res2.xml` 
- Switch to branch with only `src/main/resources/res1.xml` present 
- Invoke `dockerBuild` again
Resulting image will contain both `res1.xml` and `res2.xml`, since the outputs weren't cleared up.
Gradle's `org.gradle.language.jvm.tasks.ProcessResources` follows the similar clean up logic.
@graemerocher @melix, could it be reviewed and merged ASAP, as it hinders …
=> Fix incremental builds with dockerBuild

README.md
According to `src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java` Micronaut plugin uses `openjdk:16-alpine` as default base Docker image.
=> Fix Docker base image according to source

src/docs/asciidoc/css/guide.css, src/docs/asciidoc/css/multi-lang-sample.css
Removes the gap between code sample and `Copy to Clipboard` button.
It also removes duplicated CSS snippet.
=> Margin bottom copy to clipboard

src/docs/asciidoc/css/guide.css
Remove the list style type and margin from the table of contents 
Before: 
After:
=> remove list style type from table of contents

src/main/java/io/micronaut/gradle/MicronautApplicationPlugin.java, src/test/groovy/io/micronaut/gradle/MicronautApplicationPluginSpec.groovy
(backport of fix on 2.0.x)
This commit fixes the fact that Groovy sources (and probably Kotlin/Scala/...)
were not added to the watch paths. The problem was that the exec task was eagerly
configured. By moving to `configureEach` we're deferring the configuration to
when it's actually being requested by a user. As a consequence we are sure, when
his happens, that all plugins are applied, so the Groovy sources will be visible.
Fixes #292
=> Lazily configure the Java exec tasks

latest/guide/index.html, snapshot/guide/index.html
and from snapshot/guide to snapshot
Micronaut.io website expects the documentation to be in a subfolder named guides
=> gh-pages: redirect from latest/guide to latest

README.md, src/docs/asciidoc/index.adoc
- Add link to the 2.x version from the Asciidoc page
- Add link to the 2.x version to the main README
- Update link to the main README to the snapshot version until
we have a release verson available
=> Make documentation discoverable

src/docs/asciidoc/index.adoc
Before this PR, links to Gradle docs are wrong because they include duplicated `7.2/userguide`, like `https://docs.gradle.org/7.2/userguide/7.2/userguide/toolchains.html`.
=> Fix links to Gradle docs

src/docs/asciidoc/template/template.html
I don't think the changes done here are consistent with our navigation in other modules' documentation 
https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/295
Example of other modules:
=> remove links from navigation but api reference

gradle/libs.versions.toml, src/main/java/io/micronaut/gradle/MicronautApplicationPlugin.java
This also reworks the fix for watch paths as one of the plugins we're using triggers early realization of the `run` task.
We _cannot_ upgrade to the latest Docker plugin because it requires Java 11 and Micronaut still supports Java 8.
=> Upgrade dependencies

build.gradle, gradle/libs.versions.toml, src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, src/test/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy, src/test/groovy/io/micronaut/gradle/MicronautGraalWellBehavePluginSpec.groovy
This commit fixes the addition of the Micronaut Graal processor,
which was only done with the `library` plugin, not with the `application`.
Fixes #324
=> Fix graal processor only added with the library plugin

gradle/libs.versions.toml, samples/aot/basic-app/build.gradle, samples/aot/with-shadow/build.gradle, src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java, src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java, src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
This commit upgrades the plugin to use Micronaut AOT 1.0.0-M2,
which gives us the opportunity to add support for the built-in
`deduceEnvironment` optimization.
=> Add the `deduceEnvironment` optimization

build.gradle, settings.gradle
This removes the need to configure the test retry plugin as it's
already done by the build plugins.
=> Upgrade to build tools 5.0.2

src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java
This commit fixes a bug with optimizations not being loaded because they
would miss the default service types to check/load if the user supplies
a custom configuration file.
=> Fix configuration missing when merging user configuration with defaults

src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
Because they run in a forked process, it's useful to be able to
attach a debugger.
=> Add an option to run the AOT tasks in debug mode

build.gradle, gradle/libs.versions.toml
Log4j is a transitive dependency brought by the shadow plugin that
is used internally. While this isn't a direct threat (because a
build tool is by design an arbitrary code execution engine), security
scanners may warn about this vulnerability.
Fixes #340
=> Upgrade log4j

gradle/libs.versions.toml
> The Log4j team has been made aware of a security vulnerability, CVE-2021-45105, that has been addressed in Log4j 2.17.0 for Java 8 and up.
> Summary: Apache Log4j2 does not always protect from infinite recursion in lookup evaluation.
=> update log4j2 to 2.17.0

src/docs/asciidoc/index.adoc, src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java, src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java, src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
A project like Micronaut Security can contribute new AOT modules.
We need a user-friendly way to declare such extensions, and a way
to configure them.
This commit introduces an `aotPlugins` configuration which makes
it more obvious where to declare the AOT extensions. It also adds
a properties block to the AOT configuration, so that configuration
keys from plugins can be used without resorting to a properties
file.
=> Make it more convenient to declare AOT plugins

gradle/libs.versions.toml
https://logging.apache.org/log4j/2.x/
> Log4j 2.17.1 has been released to:
> Address CVE-2021-44832.
=> build: bump up log4j to 2.17.1

src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
The copy instructions were incorrect if the source directory was empty.
Instead of using `/*`, it should simply copy the directory. This fixes
a build problem with Oracle functions, where the source `classes` or
`resources` directories may be empty.
@pgressa as our Docker expert, I assigned you for review. It seems to work locally but I'd like to make sure you agree :)
=> Fix invalid COPY instructions

src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java, src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java, src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java, src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
This commit improves integration with Micronaut AOT by exposing 2
new configuration options:
- the "target environments", which let the user explain what
deployment environments will be, letting the analyser run with
those environments set, instead of inferring from the local one
- environment variables: this lets the user declare environment
variables which should be visible when the analysis is performed.
Those changes are required to support deployments to environments
like Oracle Cloud, for which the bean requirements are vastly
different from what you get in a local mode.
=> Improve Micronaut AOT configuration

src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java, src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
Gradle is a bit too smart with regards to up-to-date checks, and
wouldn't run the same app twice in a row if nothing changed.
Fixes #385
=> Make sure `run` tasks are always executed

aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
Once again, we're facing the fact that despite living in 2022,
Windows is still incapable of providing sensible defaults: invoking
a CLI tool with a long classpath will fail. As a consequence, we
have to invoke the AOT CLI tools with an argument file to
workaround the problem.
Fixes #397
=> Use argument file to call AOT tasks

aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java, functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy, minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
This commit fixes the AOT tasks which use `@arfile` for calling
Micronaut AOT: they suffer the same bug as in native build tools,
which is that spaces in paths need to be escaped.
See #401
=> Support spaces in paths in argfile

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy, graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
Before this change, the class used to generate native lambdas was
always set to `MicronautLambdaRuntime`, independently of the fact
that the user declared a `mainClass` or not. With this change, the
main class defined by the user will _always_ be used. Only if no
main class is set, we will default to `MicronautLambdaRuntime`.
This will require changes to Micronaut Starter.
=> Rework how the default runtime class is set for Lambda

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/FullMicronautRuntimeSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/aot/AbstractAOTPluginSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractEagerConfiguringFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/graalvm/MicronautGraalPluginSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/KotlinLibraryFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy
The Docker plugin was assuming that the GraalVM plugin was also
applied. However, this only happens if tasks are eagerly configured,
which is typically the case if you call `gradle tasks` or that
a plugin accidentally eagerly configures tasks.
Fixes #373
=> Fix docker plugin assuming graal plugin applied

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, functional-tests/src/test/groovy/io/micronaut/gradle/RuntimeDependenciesSpec.groovy, graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/Dependencies.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntime.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java
Fixes: https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/433
Adds two Micronaut runtime environments:
- LAMBDA_JAVA
- LAMBDA_PROVIDED
This matches the Lambda Runtime names:
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda.Runtime.html
```
static JAVA_11
static JAVA_8
static JAVA_8_CORRETTO
static PROVIDED
static PROVIDED_AL2
```
This allows to differentiate easily the dependencies to include automatically.
=> fix: Adds LAMBDA_JAVA and LAMBDA_PROVIDED runtimes

aot-plugin/build.gradle, docker-plugin/build.gradle, graalvm-plugin/build.gradle, gradle-plugin/build.gradle
This introduces `api` dependencies between plugins, instead of
`implementation`, so that the transitive Micronaut Gradle plugins
are on classpath when used in `buildSrc` or included builds.
Fixes #438
=> Use `api` dependencies between plugins

aot-plugin/src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java, aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java, aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, aot-plugin/src/main/java/io/micronaut/gradle/aot/NettyOptimizations.java, functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/aot/FunctionsMicronautAOTSpec.groovy, gradle/libs.versions.toml, samples/aot/basic-app/build.gradle, settings.gradle, src/docs/asciidoc/index.adoc
This commit bumps Micronaut AOT to version 1.1.0, which adds a new
optimization for Netty. This optimization is disabled by default like
the others (`starter` can enable it). Because it's likely that they
will be more Netty optimizations in the future, there's a `netty`
configuration block within the `aot` one.
=> Upgrade to Micronaut AOT 1.1.0

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy, src/docs/asciidoc/index.adoc
When a user builds a native lambda via docker, docker first pulls amazonlinux:latest
If they are on an M1, docker will pull the ARM version of amazonlinux, then later on
in the dockerfile, it will cURL and unzip the X86 version of GraalVM.
This then fails when it tries to install native-image
This fix allows us to specify an architecture of GraalVM to pull, which defaults to
that of the current system.
It effectively mirrors this change made in the maven plugin for the same issue:
https://github.com/micronaut-projects/micronaut-maven-plugin/pull/369
=> Pull GraalVM JDK based on system architecture

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
So that configurations are read eagerly (despite `configureEach`),
which can trigger an ordering issue with the micronaut configuration
not yet fully read when the dependencies are added.
Fixes #481
Verified with the reproducer at https://github.com/Gradsta/gradle-plugin-incompatibility-mcve
=> Move configuration to `afterEvaluate`

samples/test-resources/custom-test-resource/build.gradle, samples/test-resources/custom-test-resource/gradle.properties, samples/test-resources/custom-test-resource/settings.gradle, samples/test-resources/custom-test-resource/src/main/java/demo/Application.java, samples/test-resources/custom-test-resource/src/main/resources/application.yml, samples/test-resources/custom-test-resource/src/main/resources/logback.xml, samples/test-resources/custom-test-resource/src/test/java/demo/DemoTest.java, samples/test-resources/custom-test-resource/src/testResources/java/demo/GreetingTestResource.java, samples/test-resources/custom-test-resource/src/testResources/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/CustomTestResourcePluginSpec.groovy
This commit adds a `testResources` source set when applying the
test resources plugin. This makes it easy to implement custom
test resources in a single project, by implementing the test
resource resolver in `src/testResources/java` for example.
The test resources declares in that source set are automatically
added to the test resources classpath.
=> Add custom `testResources` source set

functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/Kotest5FunctionalTest.groovy, gradle-plugin/src/test/groovy/io/micronaut/gradle/MicronautApplicationPluginSpec.groovy, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautTestRuntime.java
We desire to migrate from kotest 4 to kotest 5.  This PR adds a new testRuntime option
'kotest5' which injects the correct dependencies.
I couldn't find any tests for this, and we should add it as an option to launch once
this PR is accepted and released
See discussion here https://github.com/micronaut-projects/micronaut-starter/pull/1296#pullrequestreview-1008860774
=> Add Kotest5 as a testRuntime

aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/AbstractTestResourcesSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java, samples/test-resources/data-mysql/build.gradle, test-resources-plugin/build.gradle, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/TestResourcesConfiguration.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesAOT.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
This commit integrates the test resources support with the AOT
support and GraalVM native support, so that we can run:
- optimizedRun: the standard JVM AOT-optimized run
- nativeTest: the native version of tests
- nativeOptimizedRun: the native run
all with test resources support enabled. It's worth noting
that native run support is a bit hackish, in the sense that
if you run `nativeCompile` only, then it will produce a
native binary which is for production and doesn't contain
the test resources client, as expected.
However, if you run `nativeRun`, then the test resources
client (and the properties file containing the connection
information) need to be in the binary, so `nativeCompile`
would _include_ them. This is specific of native, because
in the JVM mode, we can simply add elements to …
=> Integrate with native and AOT

functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractEagerConfiguringFunctionalTest.groovy, graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, gradle/libs.versions.toml, samples/test-resources/multiproject/app1/build.gradle, samples/test-resources/multiproject/app2/build.gradle, samples/test-resources/multiproject/app3/build.gradle, samples/test-resources/multiproject/testresources/build.gradle, src/docs/asciidoc/index.adoc, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesConsumerPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
Support application class data sharing by upgrading to Micronaut Test Resources 1.0.1.
This PR also renames the `testresources` configuration to `testResourcesService` for clarity (in a backwards compatible way). This should have been done in 3.5.0 but for some reason slipped out of the release.
=> Add support for AppCDS

src/docs/asciidoc/index.adoc
The current variant did not work for me; `buildArgs.add()` works.
```bash
$ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)
> Configure project :
[native-image-plugin] Instrumenting task with the native-image-agent: test
FAILURE: Build failed with an exception.
* Where:
Build file '/workspaces/greeting-microservice/build.gradle' line: 304
* What went wrong:
A problem occurred evaluating root project 'greeter-microservice'.
> No signature of method: build_3jy7t3tr4x9k8bhkeq65paqfe.graalvmNative() is applicable for argument types: (build_3jy7t3tr4x9k8bhkeq65paqfe$_run_closure16) values: [build_3jy7t3tr4x9k8bhkeq65paqfe$_run_closure16@43a5a2f0]
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output. …
```
=> Use buildArgs.add()

graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
The `withType` API is _eager_ so was trigerring configuration when it should avoid it.
Fixes #506
=> Fix eager configuration of some tasks

test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
=> Fix test-resources directory not created when running clean build

.github/workflows/graalvm.yml, .github/workflows/gradle.yml, .github/workflows/publish-snapshot.yml, .github/workflows/release.yml, .github/workflows/sonarqube.yml, .github/workflows/windows-ci.yml, docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/model/MicronautDockerImage.java, docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/aot/FunctionsMicronautAOTSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/aot/ShadowMicronautAOTSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/graalvm/MicronautGraalPluginSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy, graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageMultiProjectSpec.groovy, graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageTaskSpec.groovy, graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageTestTaskSpec.groovy, samples/aot/aws-function/build.gradle, samples/aot/basic-app/build.gradle, samples/aot/with-shadow/build.gradle, src/docs/asciidoc/index.adoc, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
This commit upgrades the plugin to build with Java 17, but also require everything to use Java 17 minimally: this is preparation work for supporting Micronaut 4 which will raise the minimal JDK version to 17.
This doesn't upgrade transitive plugins like the Docker plugin yet.
=> Bump minimal requirements to Java 17

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
Having ability to specify GraalVM release archive is useful in case there is a need for running offilne builds.
=> Allow to specify GraalVM releases URL

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
When running `./gradlew dockerfile` port `8080` is automatically declared as an exposed port in the `Dockerfile`.
```Dockerfile
FROM azul/zulu-openjdk-alpine:17.0.2-jre-headless
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/classes /home/app/classes
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
```
But when I run `./gradlew dockerfileNative` port `8080` is not declared.
```Dockerfile
FROM ghcr.io/graalvm/native-image:ol7-java17-22.2.0 AS graalvm
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/classes /home/app/classes
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
RUN mkdir …
```
=> Declare the same exposed port as in Dockerfile

src/docs/asciidoc/index.adoc
For the most recent release they changed "native image" to "native executable" (https://www.graalvm.org/22.2/reference-manual/native-image/) but the tech is still called Native Image
=> native image -> native executable

crac-plugin/src/main/resources/checkpoint.sh, src/docs/asciidoc/index.adoc
This allows users to restore without running docker with `--privileged`
If pid is 599 there is a low likelihood will conflict with an existing one, so CRIU does not need to fork the process or use pid namespaces to restore. This means that we can run without elevated permissions
=> Bump pid to 599 to avoid pid conflicts when restoring

test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
This commit adds a workaround specifically for IntelliJ, which generates synthetic `JavaExec` tasks whenever the user clicks on the run button of a `main` method. This task is _not_ the `run` task, so previously it didn't trigger the initialization of test resources. With this commit, we "detect" such synthetic tasks and fix the classpath of the task so that it includes the test resources properties.
=> Fix "run" task in IntelliJ

crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java, crac-plugin/src/main/resources/checkpoint.sh, src/docs/asciidoc/index.adoc
Previously, the CRaC JDK fails if using Ubuntu 22.04
After checking with the Azul team, this issue only affects Mac and WSL docker clients where the kernel has not yet been updated to support it.
This fix sets and environment variable that has no effect for previous versions, but fixes the kernel settings for 22.04.
I have made the default 22.04, and updated the docs accordingly
=> Fix CRaC for ubuntu 22.04

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
The problem described in this issue: https://github.com/bmuschko/gradle-docker-plugin/issues/1120
The newest Gradle Docker plugin introduces support for Gradle configuration cache failing during the call `dockerBuild` task. It is because the Micronaut Gradle plugin is creating the same `DockerExtension` as the original plugin is using, but without applying the plugin itself.
I think this PR should be merged together with the one which updates the dependency version: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/589
=> Fix "Cannot query the value of task ':dockerBuild' property 'dockerClientService' because it has no value available"

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCConfiguration.java, crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
If using mysql in a container, we need to be able to specify the network it is running on.
=> Allow setting a network for the crac checkpoint

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
If the user was using a custom Dockerfile (at the root of the project), then the file would be used directly, but wouldn't be found by the docker engine because living outside of the build context. This commit fixes the problem so that the file is appropriately templated and used in the build context.
Fixes #583
=> Fix custom dockerfile usage

.github/workflows/graalvm.yml, docker-plugin/src/main/java/io/micronaut/gradle/docker/tasks/BuildLayersTask.java, docker-plugin/src/test/groovy/io/micronaut/gradle/BuildLayersSpec.groovy, src/docs/asciidoc/index.adoc
This commit introduces a property to set the duplicates strategy when building the docker layers.
Fixes #584
=> Let the user specify a duplicates strategy when building layers

test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java
This is mostly useful when debugging Micronaut Test Resources itself, but it could be useful for users developing their own test resources too.
=> Add ability to debug the test resources service

functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy, gradle/libs.versions.toml, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
This commit upgrades to Micronaut Test Resources 1.1.5, which offers the ability to pass the server connection settings to the client via system properties instead of a file on classpath.
This fixes the problem of the `test` task being constantly out-of-date when the `test-resources` plugin is applied. This does **not** fix the issue with `nativeTest`, which is still out-of-date, but will require a new release of the native build tools.
Fixes #579
=> Fix `test` task being out of date with test resources

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCFinalDockerfile.java, crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
If the dockerBuildCrac task fails when generating a checkpoint, the checkpoint container remains in docker
This results in manual cleanup being required before a re-run can be performed
To fix this, this PR does not give the container a name (so it gets allocated a random one by docker)
This PR also names the image based on the project root name and path, which will prevent images potentially overwriting each other if two tasks are run at the same time on two separate projects
=> Stop container name collisions for the checkpoint container

crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracBuildTaskSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractFunctionalTest.groovy, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautBasePlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java, minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy, samples/aot/aws-function/build.gradle, samples/aot/basic-app/build.gradle, samples/aot/with-shadow/build.gradle, samples/test-resources/custom-test-resource/build.gradle, samples/test-resources/data-mysql/build.gradle, samples/test-resources/isolated-multiproject/app1/build.gradle, samples/test-resources/isolated-multiproject/app2/build.gradle, samples/test-resources/isolated-multiproject/app3/build.gradle, samples/test-resources/multiproject/app1/build.gradle, samples/test-resources/multiproject/app2/build.gradle, samples/test-resources/multiproject/app3/build.gradle, samples/test-resources/multiproject/testresources/build.gradle, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesConsumerPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
This commit fixes how the Gradle plugin integrates with Micronaut
Test Resources. The latest version of test resources makes use of
a fat jar, which allows us to inject the Micronaut Platform BOM
to the test resources service classpath, so that the inferred
dependencies, like the database drivers, can be resolved even if
the user didn't specify a particular version.
Previously to this change, it was possible that the database
drivers were accidentally resolved because the test resources
service itself was built with Micronaut, and therefore adding
the Micronaut core BOM on classpath.
@alvarosanchez you will probably need to do something similar in the Maven plugin. I think I recall we already apply the Micronaut BOM, but this has to be changed to use the Micronaut Platform BOM.
=> Fix integration with Micronaut Test Resources

buildSrc/src/main/groovy/io.micronaut.internal.build.functional-testing.gradle, functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/Kotest5FunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/KotlinLibraryFunctionalTest.groovy, gradle/libs.versions.toml, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautTestRuntime.java, minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java, minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
Adds support for configuring KSP including handling the new `inject-kotlin` module and configuring the `ksp` and `kspTest` classpaths
=> Add KSP support and re-enable Kotlin tests

test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/CustomTestResourcePluginSpec.groovy
This commit fixes the test and run tasks being up-to-date whenever a custom test resource is changed.
Fixes #619
=> Fix test/run task being up-to-date

buildSrc/src/main/groovy/io.micronaut.internal.build.gradle-plugin.gradle, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
This commit reworks how the `useJUnitPlatform()` call is made, so that it's done _when the test task is configured_, rather than in afterEvaluate. It is not strictly equivalent, especially if the user makes use (accidentally or not) of eager APIs to configure tests, but it's a low risk change, due to the fact that the previous behavior was actually broken: in Gradle 8, changing the test framework after it has been configured is an error.
Previously to this change, if the user had configured a different testing framework, then our code would have been silently ignored.
=> Fix compatibility with Gradle 8

src/docs/asciidoc/index.adoc
=> Add missing `dockerFileCrac` task description to docs

aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/tasks/DockerResourceConfigDirectoryNamer.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/tasks/PrepareDockerContext.java, functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, gradle-plugin/src/test/groovy/io/micronaut/gradle/MicronautLibraryPluginSpec.groovy, minimal-plugin/src/test/groovy/io/micronaut/gradle/MicronautMinimalLibraryPluginSpec.groovy
This commit enables use of the GraalVM metadata repository by default. It changes how the files are copied when working on Docker images, because previously, we had a single directory of resources (the generated one), but now it is possible to have multiple directories. For example, if netty is present on classpath, we will need to copy the configuration files for netty.
In practice, when we prepare the docker build context, we need to scan those directories and copy them. It is however possible that several directories have the same name, because the directory names are derived from GAV coordinates, so the same version can appear multiple times.
In order to:
- avoid overwriting configuration files for several modules which have the same version
- make things easier to debug when reading …
=> Enable GraalVM metadata repository

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautTestRuntime.java
The fix introduced in #640 fixed the problem for JUnit as a test framework, which is the default when using starter. However, it broke when using Spock or Kotest.
However, all of the test frameworks that we use require JUnit Platform. This means that the code was probably used when we supported JUnit 4 without the legacy runner, and that it can be simplified now. Basically as soon as we use a test framework we can configure JUnit Platform.
Fixes #643
=> Fix regression in test framework usage

functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy, gradle-plugin/src/test/groovy/io/micronaut/gradle/MicronautLibraryPluginSpec.groovy, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java, minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java, samples/aot/aws-function/build.gradle, samples/aot/basic-app/build.gradle, samples/aot/with-shadow/build.gradle, samples/test-resources/custom-test-resource/build.gradle, samples/test-resources/data-mysql/build.gradle, samples/test-resources/isolated-multiproject/app1/build.gradle, samples/test-resources/isolated-multiproject/app2/build.gradle, samples/test-resources/multiproject/app1/build.gradle, samples/test-resources/multiproject/app2/build.gradle
Currently the plugin always applies the old `micronaut-validation` module which means the plugin is currently broken with:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':annotationProcessor'.
> Could not find io.micronaut:micronaut-validation:.
Required by:
project :
```
This reworks the code so the validation processor is only applied if a validation module exists on the classpath
=> Rework validation module annotation processor handling

crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
The CRaC plugin uses the same directory for both the checkpoint and final dockerfiles. This is because the layers are used by both, and the checkpoint run creates a new CR directory of checkpoint data for the final image.
Gradle doesn't like this, as outputs from multiple tasks are going to the same location.
And in Gradle 8, this is an error instead of a warning in Gradle 7.
I tried to implement a better fix in multiple ways:
1. Separating the final docker-file into a different location (doesn't work, as the docker plugin cannot seem to find both it and the layer directories)
2. Copying the layers and CR directories out of docker/main into docker/main-final.  But I couldn't get this to work either.
So I went for a route that works.
This makes sure we create the main dockerfile AFTER all …
=> Fix CRaC plugin for Gradle 8

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
The image that we use, `amazonlinux:latest` was recently updated and it now fails to run the `yum` command that we used to prepare the image for installation of GraalVM.
This commit fixes the problem by using image `amazonlinux:2023` and updating the `yum` command.
=> Fix native lambda builds within Docker

.github/workflows/graalvm.yml, .github/workflows/gradle.yml, .github/workflows/sonarqube.yml, .github/workflows/windows-ci.yml, buildSrc/src/main/groovy/io.micronaut.internal.build.functional-testing.gradle, buildSrc/src/main/groovy/io.micronaut.internal.build.gradle-plugin.gradle, buildSrc/src/main/groovy/io.micronaut.internal.build.testing.gradle, crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java, docker-plugin/src/test/groovy/io/micronaut/gradle/BuildLayersSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/Kotest5FunctionalTest.groovy, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
This commit fixes a number of issues with the build:
1. reworks how the test Maven repository is built, in order to be more reliable and compatible with the configuration cache. The previous implementation didn't accurately capture changes in some cases, forcing to do a `clean` when it shouldn't be necessary
2. upgrades to AOT 2.0.0-M1
3. fixes the crac plugin using a lambda instead of anonymous class
4. fixes test expectations which were broken by recent Micronaut upgrade
=> Build fixes

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java, crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCFinalDockerfile.java, crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java, crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy
Previously, we allowed users to create `Dockerfile` and/or `DockerfileCracCheckpoint` in the root of their project and we then would attempt to use these for the image generation.
This doesn't work.  The Docker plugin requires all Docker content to be in the same file tree.
This PR copies checks for the existence of these files, and copies them to the correct location instead of building the dockerfiles.
Fixes #678
=> Copy the customized CRaC dockerfiles if they exist in the root

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
The option was incorrectly passed to the Kotlin compiler with a trailing comma in the option name. This was obviously wrong, generating wrong compiler options, and in particular something like this `micronaut.processing.group,=data-parent.doc-examples` which causes a parsing error in latest KSP plugin builds:
Wrong plugin option format: null, should be plugin:<pluginId>:<optionName>=
=> Fix micronaut.processing.group option

aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy, minimal-plugin/src/main/java/io/micronaut/gradle/AttributeUtils.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java, src/docs/asciidoc/index.adoc, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesAOT.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java
This PR fixes the broken builds.
This commit significantly reworks how configurations are setup, in order to fix a problem which appears independently in 2 locations: if using test resources or the developmentOnly configuration, it was possible that dependencies were duplicated, in different versions, on classpath.
For example, the test resources client was previously resolved independently into its own dependency graph, which was then added to the run task classpath. Similarly, the `developmentOnly` configuration was resolved independently and added to the runtime classpath.
The problem is that by appending to the classpath, we have 2 independent dependency graphs, which _may_, or may not, include the same dependencies. In practice, it was easy to get a mismatch. For example, even if we …
=> Fix duplicate entries on classpath

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautExtension.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java, minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java, src/docs/asciidoc/index.adoc, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesConsumerPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
This option has (at least) a couple use cases:
1. the issue described in #681, when a user wants to drive the Micronaut version from a catalog, or directly in their dependencies (although this is probably redundant with #694)
2. we use the Gradle plugins in our module builds, where it's going to look for the platform BOM, which is not necessarily what we want, since we want to use local versions of projects and possibly override transitive versions
Closes #681
=> Add an option to not automatically add BOM

buildSrc/build.gradle
3.7.9 release failed https://github.com/micronaut-projects/micronaut-gradle-plugin/actions/runs/4829605123/jobs/8604838345
I guess this may be the culprit
=> build: Micronaut Build Quality checks plugin to 5.4.9

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
Should we use `ol7` instead of `ol8` ? see:
https://github.com/micronaut-projects/micronaut-starter/pull/1807
=> graalvm native-image docker replace ol7 with ol8

test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/MicronautTestResourcesPluginTest.groovy
It wasn't possible to replace `2.0.0-M3` with another version because we parsed it as [2,0,3] instead, so `2.0.1` was typically considered lower.
=> Fix test resources version check

functional-tests/src/test/groovy/io/micronaut/gradle/graalvm/MicronautGraalPluginSpec.groovy, graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageTaskSpec.groovy, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java, minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
This commit changes how the `micronaut-graal` dependency is added in order to use the `AutomaticDependency` mechanism. This makes it possible to override the version of the Micronaut Graal dependency by changing the `coreVersion` in the DSL.
=> Use an automatic dependency for graal

openapi-plugin/src/main/java/io/micronaut/gradle/openapi/DefaultOpenApiExtension.java, openapi-plugin/src/test/groovy/io/micronaut/openapi/gradle/OpenApiClientGeneratorSpec.groovy, openapi-plugin/src/test/groovy/io/micronaut/openapi/gradle/OpenApiServerGeneratorSpec.groovy
While the previous implementation worked, it had a couple issues:
- we were generating the api and models in the same directory, although it was distinct classes, which breaks caching/up-to-date checking
- it compiles fine, but the IDE doesn't find the sources properly
=> Use `src/main/java` subdirectory for source directory

openapi-plugin/src/main/java/io/micronaut/gradle/openapi/DefaultOpenApiExtension.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/OpenApiSpec.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/ParameterMappingModel.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/ResponseBodyMappingModel.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/tasks/AbstractOpenApiGenerator.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/tasks/AbstractOpenApiWorkAction.java
- Add a parameter mapping model to support parameter mappings.
- Improve documentation of parameter and response body mappings and improve the api by not requiring all the properties in constructor as records did.
- Make the models serializable, as otherwise a gradle error is thrown during build.
- Rename the getUseGenerateAlwaysHttpResponse to getGenerateHttpResponseAlways
=> Improve the openapi generator plugin

functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java
If the value of the `testresources.native` flag was explicitly set to `true`, then counter-intuitively, the native test resources support was disabled. This commit therefore fixes a bug in the parsing logic, when the value `true` was effectively considered `false.
=> Fix test resources flag ignored when true

functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotSpec.groovy, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesAOT.java
The Micronaut AOT plugin is expected to be applied with the application plugin. Therefore, the test resources plugin was assuming that the application plugin was applied, but in practice a user may apply AOT with the library plugin. It wouldn't do anything, but it causes build errors.
This commit makes sure to wrap the relevant code in a `withPlugin` block to avoid the error.
Fixes #815
=> Fix error when AOT + test resources are applied with library plugin

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java, crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy
Azul added a JRE to their CRaC java deliverables.
The query wasn't specific enough to say we want a JDK, so we end up pulling the JRE if it comes back first in the response. The JRE doesn't include the JCmd command which we use for snapshotting...
This change adds `java_package_type=jdk` to the request URL so we just get the JDK.
=> Fix CRaC JDK download in docker container

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, src/docs/asciidoc/index.adoc
For both Arm and X86 we are using an alpine base image.
There is no Arm variant of Alpine, so this builds an ARM native binary, then puts it in an x86 base image.
This change switches to use `cgr.dev/chainguard/wolfi-base:latest` when the architecture is Arm.
This image was chosen due to it's size... There may be a better default choice out there...
Closes #829
=> Use an Arm compatible base image for Arm dockerBuildNative

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java, crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy, gradle/libs.versions.toml
This backports the CRaC docker fix https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/828
And the upgrade to docker https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/839
=> Backport fixes from the 4.1.x mainline to 4.0.x

src/docs/asciidoc/index.adoc
Was missing a 'tasks' section in the path
Found by MicronautFan in Discord https://discord.com/channels/1121511613250412714/1155807996140589086/1155807996140589086
Thanks! 😄 👍
=> Fix link to AbstractOpenApiGenerator

aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java, buildSrc/src/main/groovy/io/micronaut/internal/build/sourcegen/SimpleSourceProcessor.java, minimal-plugin/src/main/java/io/micronaut/gradle/ApplicationClasspathInspector.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StopTestResourcesService.java
Some plugins tasks properties were _protected_, which prevents the user from configuring them using the Kotlin DSL. There were accessible in Groovy scripts, which we use in tests, so these were unnoticed.
Revealed by comment in #785
Fixes #785
=> Make configurable fields public

aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
This PR fixes error mentioned in **Issue #803** by handling `getTargetPackage()` during `configureAotDefaults` setting `"io.micronaut.aot.generated"` as target package when main class is in the default package.
=> Fix index out of bounds if main class is not in a package

aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
Note : in order to fix all deprecations, we'll have to wait for the NBT 0.9.28 release.
=> Fix Gradle 9 deprecations

aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotSpec.groovy, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesAOT.java
The AOT process should optimize applications for the production environment. As such it doesn't make sense to have the test resources client on the classpath of the application being scanned during the AOT optimization process.
This bugfix has the potential to break builds of people who run `./gradlew build` and had builds passing because the AOT optimizer was using test resources.
Fixes #852
=> Fix test resources client on optimizer classpath

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java, docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, src/docs/asciidoc/index.adoc
This is to fix Docker builds on Apple Silicon.
Fixes #794
=> Switch to eclipse-temurin:17-jre-focal by default

gradle.properties, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautExtension.java, minimal-plugin/src/main/java/io/micronaut/gradle/internal/AutomaticDependency.java, minimal-plugin/src/test/groovy/io/micronaut/gradle/MicronautMinimalApplicationPluginSpec.groovy
In some circumstances, automatic dependencies can get in the way. This should be rare but there was no built-in mechanism to ignore such dependencies. It is now possible to list these using the `micronaut` extension, for example:
```
micronaut {
ignoredAutomaticDependencies.add("io.micronaut.data:micronaut-data-processor")
}
```
The responsibility of adding these is then shifted to the user.
Fixes https://github.com/micronaut-projects/micronaut-sql/issues/1157
=> Let the user ignore automatic dependencies

minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java, minimal-plugin/src/test/groovy/io/micronaut/gradle/AutomaticDependencySpec.groovy
closes #871
@melix @sdelamo 
micronaut-tracing and micronaut-spring have multiple possible annotation processors. I included the primary ones. Do we need to add the others? If so then the implementation needs to be changed because it's based on a map with groupIds for keys.
These are the ones I didn't add:
- io.micronaut.tracing:micronaut-tracing-opentelemetry-annotation
- io.micronaut.spring:micronaut-spring-boot-annotation
- io.micronaut.spring:micronaut-spring-web-annotation
@melix Also, I didn't see an obvious way this is tested, so I didn't change anything for the new ones either. Happy for any guidance.
=> Add missing annotation processors for micronaut modules.

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java, crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCConfiguration.java, crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java, crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy, src/docs/asciidoc/index.adoc
The Azul API has started to differentiate between linux-musl and linux-glibc.
Without us passing the option to use linux-glibc we get 2 JDKs returned, and the musl one doesn't work for building images on OSX with DockerDesktop.
This PR allows configuration of the OS when making the request to the Azul API
=> Add OS configuration for CRaC JDK

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, gradle/libs.versions.toml, minimal-plugin/build.gradle, samples/test-resources/data-mysql/src/main/resources/application.yml, samples/test-resources/isolated-multiproject/app1/src/main/resources/application.yml, samples/test-resources/multiproject/app1/src/main/resources/application.yml, src/docs/asciidoc/index.adoc
This PR uses `cgr.dev/chainguard/wolfi-base:latest` as the default base image for all CPU architectures, not only for ARM, since it is multi-platform and a bit smaller than `frolvlad/alpine-glibc`
=> Use Chainguard's Wolfi base image by default

graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java, gradle/libs.versions.toml
This version enabled the metadata repository by default so we can remove the configuration we had to do this.
In addition this sneaks in a test resources upgrade.
=> Upgrade to Native Build Tools 0.10.0

minimal-plugin/src/main/java/io/micronaut/gradle/ApplicationClasspathInspector.java
Disabled caching for the inspectClasspath task, as it's not worth caching
=> Disable caching classpath inspector

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy, src/docs/asciidoc/index.adoc
Unfortunately, libc6-dev and zlib1g-dev are not available in the Amazon Linux 2023 repository. Instead install the zlib-devel and glibc-devel packages, which are equivalent to zlib1g-dev and libc6-dev, respectively. This should be backwards compatible with Amazon Linux 2 and will also allow for using the amazonlinux:latest tag.
=> Update package names to support Amazon Linux 2023

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java, docker-plugin/src/main/java/io/micronaut/gradle/docker/model/LayerKind.java, docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
This layer is actually required for regular docker images (no optimized/AOT) since the jars which are included are not the regular jars.
Fixes #938
=> Restore "resources" layer

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
Use lazy evaluation of the layers' files to avoid triggering dependency resolution during configuration.
After upgrading to 4.3.1, I started getting the error below during configuration - the message is a bit misleading, but I think the stack points to the root cause.
```
An exception occurred applying plugin request [id: 'java-platform']
> Failed to apply plugin 'org.gradle.java-platform'.
> Project#afterEvaluate(Action) on project ':bom' cannot be executed in the current context.
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'java-platform']
...
at org.gradle.api.internal.file.CompositeFileCollection.isEmpty(CompositeFileCollection.java:66)
at io.micronaut.gradle.docker.MicronautDockerfile.setupResources(MicronautDockerfile.java:228) …
```
=> Fix dockerfile setup resources

minimal-plugin/src/main/java/io/micronaut/gradle/internal/AutomaticDependency.java, minimal-plugin/src/main/java/io/micronaut/gradle/internal/VersionCatalogLookupCache.java
This commit introduces a cache for the version catalog lookups. It appears that Gradle's findLibrary method is extremely inefficient, causing dramatic build time increases, in particular in multiproject setups.
The fix isn't great though, since it involves a static cache, but for now there's no better API until Gradle 8.7 is shipped. Even so, ideally there should be an API to get the library coordinates directly.
See https://github.com/gradle/gradle/pull/27444
See https://github.com/gradle/gradle/issues/25226
Fixes #932
=> Mitigate slow performance of `findLibrary`

functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy, functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, gradlew.bat
Micronaut 4.3.3
Micronaut-openapi 6.6.2
Spock 2.3
Gradle 8.6
=> Update libs and gradle

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java, crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy
Azul have introduced different packages for their CRaC JDK.
The first one in the list is a .deb package which we then try to unpack (and fail as it's not a tgz)
The fix here is to supply the new archive_type argument to the API to go back to a single result
=> bug: Fix the Azul API url again

src/docs/asciidoc/index.adoc
It's not clear that Kotlin code gen is supported especially because most may never look at this page for openapi code gen and rather https://openapi-generator.tech/docs/generators/ which says (Beta)
=> Add documentation around kotlin codegen support

functional-tests/src/test/groovy/io/micronaut/gradle/openapi/OpenApiClientWithKotlinSpec.groovy, gradle/libs.versions.toml, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/DefaultOpenApiExtension.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/OpenApiClientSpec.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/tasks/AbstractOpenApiWorkAction.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/tasks/OpenApiClientGenerator.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/tasks/OpenApiClientWorkAction.java, openapi-plugin/src/test/groovy/io/micronaut/openapi/gradle/OpenApiClientGeneratorSpec.groovy
Added test to clientId generator property
Fixed #949
=> Micronaut-openapi 6.7.0

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
I believe this is a typo, and instead of setCanBeConsumed twice, one should be setCanBeResolved.
This pattern can be seen in other configurations ie:
https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/2d20a5128c52aa997a36aa5d0a748f71aa6b334a/minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java#L78-L80
Closes https://github.com/micronaut-projects/micronaut-core/issues/10752
=> Mark kotlinProcessors as unresolvable

src/docs/asciidoc/index.adoc
Per https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/508:
> This PR also renames the `testresources` configuration to `testResourcesService` for clarity (in a backwards compatible way). T
=> Rename testresources to testResourcesService in doc

openapi-plugin/src/main/java/io/micronaut/gradle/openapi/DefaultOpenApiExtension.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/ParameterMappingModel.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/tasks/OpenApiClientWorkAction.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/tasks/OpenApiServerWorkAction.java
Fixed some typos
Fixed https://github.com/micronaut-projects/micronaut-openapi/issues/1623
=> Add SUPPORTING_FILES to generate for openapi client.

buildSrc/build.gradle
This dependency is no longer available on the Gradle plugin portal and makes the build fail.
See https://blog.gradle.org/portal-jcenter-impact for context.
I removed the dependency and tested docs generation as well as a user application, and I noticed no difference, so I guess it was simply redundant.
=> Remove micronaut-docs-asciidoc-extensions

functional-tests/src/test/groovy/io/micronaut/gradle/RuntimeDependenciesSpec.groovy, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
Fixes #1063 
As the [gradle documentation](https://docs.gradle.org/8.10/userguide/configuration_cache.html#config_cache:requirements:disallowed_types) states:
> Gradle model types (e.g. Gradle, Settings, Project, SourceSet, Configuration etc…​) are usually used to carry some task input that should be explicitly and precisely declared instead.
> For example, if you reference a Project in order to get the project.version at execution time, you should instead directly declare the project version as an input to your task using a Property<String>. Another example would be to reference a SourceSet to later get the source files, the compilation classpath or the outputs of the source set. You should instead declare these as a FileCollection input and reference just that.
I verified the changes by …
=> Gradle Configuration Cache fails to caches run task

test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java, test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/TestResourcesConfiguration.java
This commit adds 2 configuration properties for the test resources service, making it possible to pass either system properties or environment variables at startup.
This will be useful in order to configure the logging level of the server. For example, one can add:
```
micronaut {
testResources {
serverSystemProperties.put("logger.levels.io.micronaut", "TRACE")
}
}
```
=> Add ability to pass system properties/env vars to test resources service

gradle/libs.versions.toml, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/DefaultOpenApiExtension.java
Fix `generateHttpResponseWhereRequired` property default value
=> Micronaut openapi 6.13.1

aot-plugin/src/main/java/io/micronaut/gradle/aot/AotShadowSupport.java, aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java, minimal-plugin/src/main/java/io/micronaut/gradle/ShadowPluginSupport.java
The AOT application classpath didn't extend from `aotPlugins`, which could cause strange errors during classloading of the AOT plugins.
I have been able to test the fix on a local project, but testing in the build plugins themselves proves difficult (requires a big setup).
Without the change, running a build with a custom plugin yields:
```
Caused by: java.util.ServiceConfigurationError: io.micronaut.aot.core.AOTCodeGenerator: com.foo.MyInstropspector not a subtype
at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
at …
```
=> Fix AOT application classpath

openapi-plugin/src/main/java/io/micronaut/gradle/openapi/DefaultOpenApiExtension.java, openapi-plugin/src/main/java/io/micronaut/gradle/openapi/OpenApiSpec.java, openapi-plugin/src/test/groovy/io/micronaut/openapi/gradle/OpenApiClientGeneratorSpec.groovy, openapi-plugin/src/test/groovy/io/micronaut/openapi/gradle/OpenApiServerGeneratorSpec.groovy
Note the calls to `task.setEnabled()` which have to be done because of a side effect in Gradle. Basically we use:
javaMain.srcDir(clientSpec.getGenerateApis().zip(client.flatMap(DefaultOpenApiExtension::mainSrcDir), this::ifEnabled));
which will create a task dependency on the `client` generation task independently of the result of the `enabled` flag.
Fixes #1055
=> Offer the option to generate only APIs/models

buildSrc/src/main/groovy/io.micronaut.internal.build.functional-testing.gradle, functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/KotlinLibraryFunctionalTest.groovy, gradle/libs.versions.toml, minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
Not micronaut gradle plugin is incompatible with `kapt` plugin with version `2.2.10` because DSL was changed and now you can't use KaptArguments with non-string values.
KAPT 1.9.25:
KAPT 2.2.10:
This is crittical error, because now you can't use micronaut gradle plugin with gradle 9.0 + kotlin 2 + kapt
=> Fix for kotlin 2

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
Now youcan get Exception if write something like this:
```kotlin
tasks.withType(JavaCompile::class) {
options.encoding = "UTF-8"
options.isIncremental = true
options.isFork = true
options.compilerArgs = listOf(
"-parameters",
"-Xlint:unchecked",
"-Xlint:deprecation",
)
}
```
Because `listOf` in kotlin is immutable. 
Also need to check `-parameters` - maybe it's already in list
=> Added protection from immutable lists in compiler args

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautTestRuntime.java
Older Gradle releases used to add this dependency automatically. Since Gradle 8, this is no longer the case (see https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#manually_declaring_dependencies).
However, Native Build Tools used to leak this dependency, which caused other issues like duplicate entries on classpath. Since we upgraded to 0.11.1, this is no longer the case.
Therefore, users who upgrade may see an error if they don't add this dependency explicitly. To workaround this and make transition smoother, we're adding the dependency back implicitly.
=> Automatically add `junit-platform-launcher`
