micronaut-projects/micronaut-gradle-plugin

src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java

Only check the target byte code level

---

src/main/java/io/micronaut/gradle/MicronautLibraryPlugin.java
src/test/groovy/io/micronaut/gradle/MicronautLibraryPluginSpec.groovy

Fix JUnit 5 platfom config

---

README.md
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

Fixes #74
- typo
- Allow setting the main of native image to something else. Fixes #74

Allow setting the main of native image to something else.

---

src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java

Switch to openjdk:15-alpine

---

README.md
build.gradle
src/main/java/io/micronaut/gradle/MicronautApplicationPlugin.java
src/main/java/io/micronaut/gradle/MicronautLibraryPlugin.java

Fixes #72
- typo
- Move shadow config to library plugin

Move shadow config to library plugin

---

src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java

Use output resources directory path. Fixes #114

---

README.md
src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

This fixes the issues found with the original implementation, where the DockerBuildStrategy wasn't taken into account correctly & also the args.

Feature/allow additional docker commands + fix

---

src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java

These I missed during the first implementation, but now tested ... sorry for the mistake.

Found that the logic was wrong for the check if there was a dockerfile or not.

---

src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

Found that my original implementation was adding too many workarounds, and decided to rework it using primarily the original implementation, but with a different entry point and evaluation time.

Rework the implementation to allow additional commands to be supplied.

---

src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

This PR enables the generation of [mostly static native images](https://www.graalvm.org/reference-manual/native-image/StaticImages/#build-a-mostly-static-native-image) and switch from an alpine-glibc docker image to a distroless one.
Superseedes #126

Build mostly static native images and use distroless docker image

---

README.md
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

Build GraalVM dynamically-linked native images by default

---

src/main/java/io/micronaut/gradle/MicronautLibraryPlugin.java

Add missing `-parameters` for JavaCompile task

---

src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java
src/test/groovy/io/micronaut/gradle/NativeImageTaskSpec.groovy

Use dummy task and don't mutate actual native image task. Fixes #157

---

.github/workflows/graalvm.yml
.github/workflows/windows-ci.yml
src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java
src/test/groovy/io/micronaut/gradle/BuildLayersSpec.groovy
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
src/test/groovy/io/micronaut/gradle/NativeImageMultiProjectSpec.groovy
src/test/groovy/io/micronaut/gradle/NativeImageTaskSpec.groovy
src/test/groovy/io/micronaut/gradle/NativeImageTestTaskSpec.groovy

Fix directory locking issue on Windows & build directory location

---

build.gradle
src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java
src/test/groovy/io/micronaut/gradle/DockerfileSpec.groovy
src/test/groovy/io/micronaut/gradle/NativeImageMultiProjectSpec.groovy
src/test/groovy/io/micronaut/gradle/NativeImageTaskSpec.groovy

Fixes https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/193

Fix native image for multiproject builds

---

src/main/java/io/micronaut/gradle/MicronautApplicationPlugin.java

Fix for #198
From my tests `sourceSet.getAllSource()` contains Java, Kotlin and Resource folders. Basically, the same behavior as a former "src/main".
Stream API was used in the source before. 
`import java.util.stream.Collectors` is new here, though already used by the `micronaut-core`.
`sourceSets.findByName("main");` is `@Nullable` from the source code. Not sure about the correct behavior here, just added a conditional guard, as in the nearest `configureLogging()` method. Lack of `"main"` sound like very exotic and will break some not related parts of the code anyway.
I tried to add test around it, but it looks like there are no simple way to interrupt `--continuous` task.

Fix hardcoded "/src/main" srcDir for continuous restart watcher (#198)

---

src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

Run docker apps with a user instead of root

---

src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java

Also see https://github.com/micronaut-projects/micronaut-maven-plugin/pull/214 and https://github.com/micronaut-projects/micronaut-starter/pull/895

Oracle cloud function native image fixes

---

build.gradle

This should fix the sync'ing of common files PR: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/242

Add placeholder dependency updates task

---

src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

This is a cleaned up version of #245 
Closes #237

Support custom entry points

---

build.gradle

This commit introduces a dummy docs task, so that it works with CI
and that we can replace it with a proper documentation task later.

Prepare "docs" task

---

README.md
src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java

Upgrade base docker image to Java 17

---

src/docs/asciidoc/css/guide.css

css to style asciidoc tips

---

src/docs/asciidoc/template/template.html

fix: broken foundation image

---

src/docs/asciidoc/css/guide.css

better margins

---

src/docs/asciidoc/index.adoc

There was some information regarding the internal changes, but no particular instruction about how to switch from one DSL to the other.
Once this is merged I will proceed with the 3.0.0 release.

Add upgrade notes

---

src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java

In some unclear circumstances, there's a possibility that the
`getElements` collection returns the same task several times.
In order to avoid registering the same test task multiple times,
we're adding a filter.
Fixes #303

Fix duplicate registration of test task

---

src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java

This workaround will be removed once we upgrade to the native build tools 0.9.9.
Fixes #306

Workaround for the test resources directory potentially empty

---

.github/workflows/gradle.yml
gradle/wrapper/gradle-wrapper.properties

Update common files

---

gradle/libs.versions.toml
src/docs/asciidoc/index.adoc

Fixes https://github.com/micronaut-projects/micronaut-aot/issues/40

Upgrade to native build tools 0.9.9

---

src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java

For the AOT optimized run, we put the optimized jar on classpath,
so the output of the main source set must not be added, otherwise
resources would appear twice.
Fixes #351

Filter out main source set output from optimized run

---

src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java

So that this lifecyle task also builds optimized jars

Make the created jar tasks a dependency of assemble

---

samples/aot/aws-function/build.gradle
samples/aot/aws-function/settings.gradle
samples/aot/aws-function/src/main/java/example/micronaut/Book.java
samples/aot/aws-function/src/main/java/example/micronaut/BookRequestHandler.java
samples/aot/aws-function/src/main/java/example/micronaut/BookSaved.java
samples/aot/aws-function/src/main/resources/application.yml
samples/aot/aws-function/src/main/resources/logback.xml
samples/aot/aws-function/src/test/java/example/micronaut/BookRequestHandlerTest.java
src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java
src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
src/test/groovy/io/micronaut/gradle/aot/FunctionsMicronautAOTSpec.groovy

This commit adds initial support for optimizing Micronaut libraries,
in particular functions. For now tests limited to lambdas, but
deployment is **not** tested yet.

Add support for optimizing lambdas

---

gradle/libs.versions.toml
samples/aot/aws-function/build.gradle
samples/aot/basic-app/build.gradle
samples/aot/with-shadow/build.gradle
src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java
src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java

- Upgrade to Micronaut 3.3.0
- Upgrade to Micronaut AOT 1.0.0-M7

Bump dependencies

---

src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java

Fix native docker file using wrong paths under Windows

---

functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy
gradle/libs.versions.toml
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java

This commit fixes shadow jar building, by making sure that the generated
jar merges service files.
Fixes #406

Fix service files not merged with shadow plugin

---

gradle/libs.versions.toml
src/docs/asciidoc/index.adoc

Upgrade to Native Build Tools 0.9.11

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/DockerBuildOptions.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy

This commit adds the ability to choose in which target directory
the application will be put inside a docker container.
Fixes #402

Add support for configuring target working directory

---

functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
minimal-plugin/src/main/java/io/micronaut/gradle/ShadowPluginSupport.java

Fixes https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/406

fix: shadowJar.mergeServiceFiles also for library

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java

This reverts commit 80faf6e2bce41f6f5d36feebc6fdf8b718fec0c6.

Revert "Rework how the default runtime class is set for Lambda (#415)"

---

.github/workflows/graalvm.yml
.github/workflows/gradle.yml
buildSrc/src/main/groovy/io.micronaut.internal.build.testing.gradle
settings.gradle

Upgrade build tools to 5.3.4

---

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java

Fix typo in property name

---

gradle/libs.versions.toml
test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java

Tweak test resources service startup options

---

.github/workflows/sonarqube.yml
docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy

Upgrade default GraalVM version to 22.2

---

src/docs/asciidoc/index.adoc

so they match https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/gradle/libs.versions.toml#L8

doc: correct native-build-tools-version

---

src/docs/asciidoc/index.adoc

Close https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/544
- [task name is dockerCracBuild not cracDockerBuild](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/545/commits/27b994268715d88fe4807b95240e479543c4445e)
- [document task dockerBuildCrac](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/545/commits/6f1a0a5eb60eb11435309ec044cee9158c0b7be2)
- [document dockerPushCrac task](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/545/commits/96ebc0f7e5640c0bc3a562cd46d931c162b273b1)

improve Crac Tasks Documentation 

---

test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java

So that it survivces `clean`
Fixes #591

Move the test resources port file outside the build directory

---

gradle/libs.versions.toml

Upgrade to Micronaut Test Resources 1.2.3

---

.github/workflows/sonarqube.yml
docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
src/docs/asciidoc/index.adoc

I think we should create a new minor 3.7.x and merge this Pr into that branch.

update to graal 22.3.0

---

crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java
crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
gradle/libs.versions.toml
settings.gradle

Supercedes #589
There is probably more work to do on our docker plugin to better support lazy configuration, but this goes beyond the scope of this PR.

Upgrade to Docker plugin v9

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy

Close #691 
Lambda runs on Amazon linux 2

Revert to amazon linux 2

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy

Fix empty RUN command

---

.github/workflows/graalvm-dev.yml
.github/workflows/graalvm-latest.yml
.github/workflows/gradle.yml

The [files-sync](https://github.com/micronaut-projects/micronaut-project-template/blob/master/.github/workflows/files-sync.yml) github job from `micronaut-project-template` doesn't sync files for `micronaut-gradle-plugin` so added changes manually.

Manual sync of graalvm workflows

---

aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
aot-plugin/src/test/groovy/io/micronaut/gradle/aot/AotOptimizerConfigurationSpec.groovy

Make it possible to pass JVM arguments to AOT process

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
gradle/libs.versions.toml
minimal-plugin/build.gradle

Upgrade to Alpine 3.16

---

src/docs/asciidoc/index.adoc

As discussed in https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/799 we will document how to change this.

Add documentation on how to switch amazonlinux image for lambdas

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java

Fixes native build on Windows. The fixes are related to the fact that the separator is `\` on Windows:

Fix native build on Windows

---

aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
samples/aot/basic-app/build.gradle
samples/aot/basic-app/src/main/resources/logback.xml

Use optimized jar for building the optimized native binary

---

aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
buildSrc/src/main/groovy/io.micronaut.internal.build.gradle-plugin.gradle
gradle/wrapper/gradle-wrapper.properties
minimal-plugin/src/main/java/io/micronaut/gradle/AttributeUtils.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java

This is to find potential problems before final version.
Fixes #837

Upgrade to Gradle 8.4-rc-1

---

functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/KotlinLibraryFunctionalTest.groovy
graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
gradle/libs.versions.toml
minimal-plugin/src/main/java/io/micronaut/gradle/AnnotationProcessing.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautBasePlugin.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautExtension.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
minimal-plugin/src/main/java/io/micronaut/gradle/SourceSetConfigurer.java
minimal-plugin/src/main/java/io/micronaut/gradle/SourceSetConfigurerRegistry.java
minimal-plugin/src/test/groovy/io/micronaut/gradle/MicronautDeprecationsPluginSpec.groovy

Upgrade to Kotlin plugin 1.9.20

---

openapi-plugin/src/main/java/io/micronaut/gradle/openapi/DefaultOpenApiExtension.java
openapi-plugin/src/main/java/io/micronaut/gradle/openapi/OpenApiExtension.java
openapi-plugin/src/test/groovy/io/micronaut/openapi/gradle/OpenApiClientGeneratorSpec.groovy
openapi-plugin/src/test/groovy/io/micronaut/openapi/gradle/OpenApiServerGeneratorSpec.groovy

Add overloads for local files in OpenAPI extension

---

crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracBuildTaskSpec.groovy

For some reason, we are no longer copying the libs and resources into the final CRaC image.
This PR remedies that

bug: copy layers into final crac image

---

functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
src/docs/asciidoc/index.adoc

Also added a test (so I could check my docs were right).

Document the jdkVersion property for dockerfileNative

---

gradle/libs.versions.toml

This fixes compatibility with GraalVM 22.

Upgrade to Micronaut AOT 2.3.0

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
src/docs/asciidoc/index.adoc

- fixes issues with aarch64 oraclecloud serverless function native image 
- fixes issues and adds jdk 21 support for oraclecloud functions

fix oraclecloud functions

---

src/docs/asciidoc/index.adoc

Document multiple OpenAPI client/server generation

---

functional-tests/src/test/groovy/io/micronaut/gradle/settings/VersionOverrideFunctionalTest.groovy
platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/MicronautCatalogSettingsPlugin.java

The Micronaut Gradle plugin provided a way to override versions defined in the Micronaut platform catalog (named "mn") using a specific file called `gradle/mn-override.versions.toml`. However, there was no such mechanism for other catalogs imported from a remote repository (for example a user may import a corporate catalog file). This commit expands our override logic so that it can handle any catalog by convention. The override file name is `<catalog>-override.versions.toml`.

Support overriding versions from any imported catalog

---

functional-tests/src/test/groovy/io/micronaut/gradle/FullMicronautRuntimeSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/RuntimeDependenciesSpec.groovy
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntime.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java
minimal-plugin/src/test/groovy/io/micronaut/gradle/MicronautRuntimeSpec.groovy
src/docs/asciidoc/index.adoc

Add a runtime based on this HTTP POJA: https://github.com/micronaut-projects/micronaut-servlet/pull/773
The module was not yet published, so this cannot be merged yet.

Add HTTP POJA runtime

---

gradle/libs.versions.toml
test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java

This commit ugprades to the latest test resources in order to fix the control panel support.

Fix integration with control panel

---

gradle/libs.versions.toml
test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java

The previous default version has an annoying bug, which surfaced when running on GitHub actions in private repositories.

Upgrade Micronaut Test Resources

---

functional-tests/src/test/groovy/io/micronaut/gradle/FullMicronautRuntimeSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/RuntimeDependenciesSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy
gradle/libs.versions.toml
minimal-plugin/src/main/java/io/micronaut/gradle/ShadowPluginSupport.java
samples/aot/aws-function/build.gradle
samples/aot/with-shadow/build.gradle
src/docs/asciidoc/index.adoc

Migrate to new shadow plugin `com.gradleup.shadow` (https://github.com/GradleUp/shadow)

---

build.gradle
src/docs/asciidoc/index.adoc

Document AOT shadow jar and fix javadoc generation

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/DockerExtension.java
docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy

Add shortcut for disabling use of `COPY --link`

---

src/docs/asciidoc/index.adoc

addressing [this issue](https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/1093)

Adding jsonschema to individual plugins

---

minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java

Fixes https://github.com/micronaut-projects/micronaut-core/issues/11716

Add countermeasures for Lombok users

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/editor/DefaultEditor.java
docker-plugin/src/test/groovy/io/micronaut/gradle/docker/editor/DefaultEditorTest.groovy

See https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/1118.

Fixes bug when inserting 'before' using 'editDockerfile' #1118.

---

functional-tests/src/test/groovy/io/micronaut/gradle/FullMicronautRuntimeSpec.groovy
functional-tests/src/test/groovy/io/micronaut/gradle/RuntimeDependenciesSpec.groovy
gradle/libs.versions.toml
jsonschema-plugin/src/test/resources/refFolder/ref/types/cheatsheet.schema.json
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntime.java
minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java
minimal-plugin/src/test/groovy/io/micronaut/gradle/MicronautRuntimeSpec.groovy
src/docs/asciidoc/index.adoc

https://micronaut-projects.github.io/micronaut-servlet/latest/guide/#httpServer
Close: https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/1109

Built-In Java HTTP Server Runtime

---

minimal-plugin/src/main/java/io/micronaut/gradle/ShadowPluginSupport.java

Fix compatiblity with shadow plugin v9

---

docker-plugin/src/main/java/io/micronaut/gradle/docker/editor/DefaultEditor.java
docker-plugin/src/test/groovy/io/micronaut/gradle/docker/editor/DefaultEditorTest.groovy

See https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/1118. Original fix was incorrect. PR replaces Dockerfile used by test to one which is more realistic. This would have highlighted the problem with the original fix.

Fixes bug when inserting 'before' using 'editDockerfile' micronaut-projects#1118
